name: docker-cli
permissions:
  contents: read
  packages: write # needed to upload docker images

on:
  push:
    tags:
      - '*'
  schedule:
    # Run a bit later than release-dev
    - cron: "0 7 * * 2,3,4,5,6"
  workflow_dispatch:
    inputs:
      skip_release:
        description: "Skip releasing the cli"
        default: false
        type: boolean

jobs:
  docker-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        timeout-minutes: 3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Determine active tag
        id: analyze
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            tag=${GITHUB_REF#refs/tags/}
            echo "tag=$tag"
            echo "release=$tag Release"
            echo "notes=Release $tag of the Docker-based Temper CLI tool;"\
              "the CLI is still under development."
          else
            echo "tag=dev"
            echo "release=Nightly Release"
            echo "notes=Nightly release of the Docker-based Temper CLI tool;"\
              "this has not been manually tested."
          fi | tee -a "$GITHUB_OUTPUT"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        timeout-minutes: 3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        timeout-minutes: 3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        timeout-minutes: 3
      # The set up jdk operation also creates a toolchains.xml file for maven.
      - name: Set up JDK
        uses: actions/setup-java@v4
        timeout-minutes: 3
        with:
          distribution: "zulu"
          java-version: |
              17
      # Use the official Gradle action for better caching
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        timeout-minutes: 3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: docker/src/go.mod
          cache-dependency-path: |
            docker/go.work.sum
            docker/src/go.sum
        timeout-minutes: 3

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libbtrfs-dev libdevmapper-dev
          version: cache # cache version
        timeout-minutes: 3

      - name: Build and push the multiplatform CLI image
        env:
          DOCKER_CLI_TAG: cli-${{ steps.analyze.outputs.tag }}
        run:
          ./gradlew cliImageMultiplatformCreate
        timeout-minutes: 30

      - name: Build the runners
        env:
          DOCKER_CLI_TAG: cli-${{ steps.analyze.outputs.tag }}
        run:
          ./gradlew runnerAll
        timeout-minutes: 15

      - name: Zip the runners
        run: |
          cd docker &&
            for run in temper-docker-*; do
              zip -9 "${run%.*}".zip "$run"
            done

      - name: Create release
        if: ${{ ! inputs.skip_release }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.analyze.outputs.tag }}
          name: ${{ steps.analyze.outputs.release_name }}
          repository: temperlang/temper-docker
          # permissions content:read,write workflow:read,write
          # repos: temper-docker, jre4temper
          # poc: ben@
          token: ${{ secrets.CROSS_REPO_POST_RELEASE }}
          body: |
            ${{ steps.analyze.outputs.notes }}
            For build details, see the [source run][run].

            [run]: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          files: ./docker/temper-docker-*.zip
          prerelease: ${{ steps.analyze.outputs.tag == 'dev' }}
          fail_on_unmatched_files: true
          make_latest: ${{ steps.analyze.outputs.tag != 'dev' }}
